### ISSUE TITLE
Rename organization from nix-basement to nix-prefab

### ISSUE THREAD

**Issue by lukas-mertens** [nix-prefab/nix-basement#40]
If possible, we should use some kind of migration path to prevent users who might already be using nix-basement in their project, from running to problems. I think github does an automatic redirect for some time, right?

**Comment by nzbr** [comment]
Until someone else claims the organization name iirc

**Comment by lukas-mertens** [comment]
@nzbr then we should probably do it now, right? Better now than later...

**Comment by nzbr** [comment]
Done
